version: '3'
services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/iTerminator
      - vendor-volume:/var/iTerminator/vendor

  httpd:
    image: httpd:2.4
    volumes:
      - ./web/:/usr/local/apache2/htdocs/

volumes:
  vendor-volume: