aws:
    version: latest
    region: %aws_region%
    credentials:
        key: %aws_key%
        secret: %aws_secret%
    s3:
        version: '2006-03-01'

services:
    aws.credentials:
        class: Aws\Credentials\Credentials
        arguments:
            - %aws_key%
            - %aws_secret%